### ISSUE TITLE
shep logs has nasty errors on never run functions

### ISSUE THREAD

**Issue by chris-olszewski** [bustle/shep#234]
If a function has never been run then the user will see `Error: No log groups found for specified function` this could probably be prettier.

Also as @reconbot pointed out, if a specific version of a function has never been ran then the user gets a cryptic
```
InvalidParameterException: 1 validation error detected: Value '[]' at 'logStreamNames' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (/Users/wizard/src/gradius/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/wizard/src/gradius/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/wizard/src/gradius/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/wizard/src/gradius/node_modules/aws-sdk/lib/request.js:678:14)
```

I think we should catch these and display something along the lines of "Logs for the version of the function you requested don't exist yet"

**Comment by chris-olszewski** [comment]
This was resolved somewhere in time
